# This file contains default values for all
# variables testcases use ...

debug = False
debugstatus = False
uboot_strings = ['Autobooting in', 'noautoboot',  'autoboot', 'EOF', 'RomBOOT']
uboot_autoboot_key = ''
state_uboot_timeout = 1
tb_power_state = 'undef'
term_line_length = '200'
wdt_timeout = '120' # wdt timeout after 2 minutes
state_linux_timeout = 4
labsshprompt = '$ '
tc_return = True
tc_workfd_check_if_cmd_exist_cmdname = 'none'
tc_lx_mount_dev = '/dev/sda1'
tc_lx_mount_fs_type = 'ext4'
tc_lx_mount_dir = '/home/hs/mnt'
tc_lx_bonnie_dev = tc_lx_mount_dev
tc_lx_bonnie_sz = '968'
ub_boot_linux_cmd = 'run tbot_boot_linux'
do_connect_to_board = True
tftpboardname = 'config.boardname'
boardlabname = 'config.boardname'
boardlabpowername = 'config.boardname'
tftpboardrootdir = ''
tc_lab_toolchain_rev = "5.4"
tc_lab_toolchain_name = "armv5te"
tc_lx_gpio_nr = '69'
tc_lx_gpio_dir = 'out'
tc_lx_gpio_val = '1'
tc_lx_eeprom_file = '/sys/class/i2c-dev/i2c-0/device/0-0050/eeprom'
tc_lx_eeprom_tmp_dir = 'config.lab_tmp_dir'
tc_lx_eeprom_wp_gpio = 'none'
tc_lx_eeprom_wp_val = "0"
tc_lx_eeprom_wp_sz = "4096"
tc_lx_eeprom_wp_obs = "32"
tc_lx_eeprom_wp_wc = "128"
tc_lx_cpufreq_frequences = ['294']
tc_lx_check_usb_authorized = 'usb 1-1'
tc_workfd_check_if_file_exists_name = "bonnie++-1.03e.tgz"
tc_workfd_check_if_dir_exists_name = "mtd-utils"
tc_lx_dmesg_grep_name = "zigbee"
tc_lx_readreg_mask = "0x000000ff"
tc_lx_readreg_type = "w"
tc_lx_create_reg_file_name = "pinmux.reg"
tc_lx_create_reg_file_start = "0x44e10800"
tc_lx_create_reg_file_stop = "0x44e10a34"
tc_lx_regulator_nrs = ['0 regulator-dummy -', '1 hsusb1_vbus 5000000',
		'2 vmmc 3300000', '3 pbias_mmc_omap2430 3000000',
		'4 DCDC1 1200000', '5 DCDC2 3300000', '6 DCDC3 1800000',
		'7 LDO1 1800000', '8 LDO2 3300000']
lab_bdi_upd_uboot_bdi_cmd = 'telnet bdi6'
lab_bdi_upd_uboot_bdi_prompt = 'BDI>'
lab_bdi_upd_uboot_bdi_era = 'era'
lab_bdi_upd_uboot_bdi_prog = 'prog 0xfc000000'
lab_bdi_upd_uboot_bdi_file = '/tftpboot/tqm5200s/tbot/u-boot.bin'
lab_bdi_upd_uboot_bdi_run = [{'cmd':'res run', 'val':'resetting target passed'}]
tc_ubi_cmd_path = "/work/tbot/mtd-utils"
tc_ubi_mtd_dev = "/dev/mtd4"
tc_ubi_ubi_dev = "/dev/ubi0"
tc_ubi_min_io_size = "1024"
tc_ubi_max_leb_cnt = "100"
tc_ubi_leb_size = "126976"
tc_ubi_vid_hdr_offset = "default"
tc_lx_ubi_format_filename = "/home/hs/ccu1/ecl-image-usbc.ubi"
tc_workfd_apply_patchwork_patches_list = []
tc_workfd_apply_patchwork_patches_list_hand = []
tc_workfd_apply_patchwork_patches_blacklist = []
tc_workfd_apply_patchwork_patches_checkpatch_cmd = 'none'
tc_workfd_apply_patchwork_patches_eof = 'yes'
tc_workfd_get_patchwork_number_list_order = '-delegate'
tc_workfd_rm_file_name = 'none'
tc_workfd_cd_name = 'none'
tc_lab_get_linux_source_git_repo = "/home/git/linux.git"
tc_lab_get_linux_source_git_repo_user = 'anonymous'
tc_lab_get_linux_source_git_branch = "master"
tc_lab_get_linux_source_git_reference = 'none'
tc_workfd_apply_local_patches_dir = 'none'
tc_workfd_apply_local_patches_checkpatch_cmd = 'none'
tc_workfd_apply_local_patches_checkpatch_cmd_strict = "no"
tc_workfd_get_list_of_files_mask = '*'
tc_workfd_compile_linux_boardname = 'config.boardname'
tc_workfd_compile_linux_clean = 'yes'
tc_workfd_compile_linux_modules = 'none'
tc_workfd_compile_linux_modules_path = 'none'
tc_workfd_compile_linux_dt_name = 'none'
tc_workfd_compile_linux_append_dt = 'no'
tc_workfd_compile_linux_load_addr = 'no'
tc_workfd_compile_linux_make_target = 'uImage'
tc_workfd_compile_linux_fit_its_file = 'no'
tc_workfd_compile_linux_fit_file = 'no'
tc_workfd_compile_linux_mkimage = '/home/hs/i2c/u-boot/tools/mkimage'
tc_workfd_compile_linux_makeoptions = ''
workfd_get_patchwork_number_user = 'hs'
workfd_get_patchwork_number_list_order = '-delegate'
tc_workfd_connect_with_kermit_ssh = "none"
tc_workfd_connect_with_kermit_sudo = "none"
tc_workfd_connect_with_kermit_rlogin = "none"
kermit_line = '/dev/ttyUSB0'
kermit_speed = '115200'
tc_lab_denx_power_tc = 'tc_lab_denx_power.py'
tc_lab_denx_get_power_state_tc = 'tc_lab_denx_get_power_state.py'
tc_lab_denx_connect_to_board_tc = 'tc_lab_denx_connect_to_board.py'
tc_lab_denx_disconnect_from_board_tc = 'tc_lab_denx_disconnect_from_board.py'
tc_lx_trigger_wdt_cmd = '/home/hs/wdt &'
tc_workfd_create_ubi_rootfs_path = '/opt/eldk-5.4/armv7a-hf/rootfs-minimal-mtdutils'
tc_workfd_create_ubi_rootfs_target = '/tftpboot/dxr2/tbot/rootfs-minimal.ubifs'
workfd_ssh_cmd_prompt = '$'
workfd_ssh_cmd_opt = ''
linux_prompt_default = 'root@generic-armv7a-hf:~# '
labprompt = 'config.linux_prompt'
linux_user = 'root'
create_dot = 'no'
create_statistic = 'no'
create_dashboard = 'no'
create_webpatch = 'no'
create_html_log = 'no'
create_documentation = 'no'
event_documentation_strip_list = []
switch_su_board = 'lab'
tc_workfd_can_ssh = 'no'
tc_workfd_can_ssh_prompt = '$'
tc_workfd_can_su = 'no'
tc_workfd_can_dev = 'can0'
tc_workfd_can_bitrate = '500000'
tc_workfd_can_iproute_dir = '/home/hs/iproute2'
tc_workfd_can_util_dir = '/home/hs/can-utils'
tc_workfd_hdparm_path = '/home/hs/shc/hdparm-9.50/'
tc_workfd_hdparm_dev = '/dev/mmcblk1'
tc_workfd_hdparm_min = '12.0'
tb_set_after_linux = ''
